SC-2555 Mark pipeline as unstable when running Java < 11
SonarSource/sonar-scanner-jenkins pull request #169
Opened 2020-10-27 07:30 UTC by tom-vanbraband-sonarsource

The SonarCloud scanner logs a warning message when the scanner is executed with a Java version under 11. This change will mark the pipeline as unstable if it can find that log message. 

We saw from data that mainly Jenkins users are not making the switch to Java 11 so that's why we decided to focus on Jenkins specifically.

2020-10-27 08:19 UTC, mark-rekveld-sonarsource requested changes
The solution looks good. You do seem to have some build issues to fix.

2020-10-27 08:19 UTC, mark-rekveld-sonarsource commented on src/main/java/hudson/plugins/sonar/utils/SonarUtils.java
> +    if (java11Warning && (result == null || !result.equals(Result.FAILURE))) {
You could simply this to `java11Warning && Result.FAILURE.equals(result)`

2020-10-27 09:24 UTC, tom-vanbraband-sonarsource commented
@mark-rekveld-sonarsource the ITs are failing with the message:
```
java.lang.IllegalArgumentException: workflow-aggregator plugin not installed
```

I don't see how my change could have triggered that failure, do you have any idea what the cause might be?

2020-10-27 09:50 UTC, mark-rekveld-sonarsource commented
> I don't see how my change could have triggered that failure, do you have any idea what the cause might be?

I looked at the junit report for the test run and it seems that there are dependencies of the workflow-aggregator plugin that are not loading correctly. Looks like someone in Jenkins land published a new version of the plugin that is breaking our tests.

I have not yet found a solution to pinning plugin versions used in the tests

2020-11-05 16:44 UTC, mark-rekveld-sonarsource commented
@tom-vanbraband-sonarsource I committed a Jenkins version bump since I suspect this will fix the build. A more specific dependent plugin versions spec didn't get me a green build locally, so we are stuck with bumping Jenkins itself.

2020-11-06 07:42 UTC, tom-vanbraband-sonarsource commented
@mark-rekveld-sonarsource thanks a lot! This PR is ready to be merged and released from my side, let me know if I can help with anything!

2020-11-06 08:08 UTC, mark-rekveld-sonarsource approved these changes

2020-11-06 08:09 UTC, merged