[JENKINS-69464] Cannot configure msBuildSQRunnerInstallation global tool using JCASC
SonarSource/sonar-scanner-jenkins pull request #249
Opened 2023-03-10 00:17 UTC by nfalco79

Add annotation on MsBuildSQRunnerInstallation default constructor to instruct the CasC plugin that home variable is optional and not required.
Add CasC test cases for both MsBuildSQRunnerInstallation and SonarRunnerInstallation

- [X] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [X] Provide a unit test for any code you changed

2023-03-13 11:11 UTC, nfalco79 commented
This PR add a CheckForNull annotation and related test for Jenkins CasC plugin so the jenkins helm chart does not fail on startup (blocking bug)

2023-03-16 09:21 UTC, leo-geoffroy-sonarsource commented
hello @nfalco79 
Could you provide a step by step reproducer for the bug you encountered?
From my understanding, you install jenkins with helm chart and enable sonar-jenkins-plugin via jcasc/helm chart values?
thanks

2023-03-17 21:26 UTC, nfalco79 commented
Yes, using the jenkins helm chart and configure the msbuild sonar scanner in the tools section.
For the best understanding look test cases in the pr (also the yam file in test resources). Run tests without the changes to the Installer file and will get the exception about home attribute is required. It must not when I choose the sonar scanner version from the combo box. It is required when i provide an URL where download the tool than the home is required. Anyway the changes reflext the same of Sonar Scanner installer where it already work great

2023-03-21 13:27 UTC, jacek-poreda-sonarsource requested changes
Few small fixes, and should be ready to go

2023-04-05 07:29 UTC, jacek-poreda-sonarsource commented
Hello @nfalco79 , 
Thanks a lot for those fixes.

Currently, we have issues with our pipeline to run your PR against our ITs, please be patient - I will get back to your PR once we fix them.

2023-05-05 09:55 UTC, nfalco79 commented
@jacek-poreda-sonarsource any movement on this?

2023-05-08 11:23 UTC, jacek-poreda-sonarsource approved these changes
@nfalco79 LGTM!

2023-05-08 11:23 UTC, jacek-poreda-sonarsource approved these changes
@nfalco79 LGTM!

2023-05-08 11:24 UTC, merged